server:
  port: 9527

spring:
  application:
    name: QuizHub-Gateway

  cloud:
    gateway:
      routes:

        - id: QuizHub-User
          uri: lb://QuizHub-User
          predicates:
            - Path=/users/**

        - id: QuizHub-UAA
          uri: lb://QuizHub-UAA
          predicates:
            - Path=/auth/github
            - Path=/auth/login
            - Path=/auth/register

        - id: QuizHub-GitServer
          uri: lb://QuizHub-GitServer
          predicates:
            - Path=/git/**



      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 #默认端口，如果被占用就会+1慢慢找

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

info:
  module:
    name: QuizHub-Gateway
    version: 1.0
  authur: Lehr

management:
  endpoints:
    web:
      exposure:
        #默认暴露所有监控点
        include: '*'

