server:
  port: 9527

spring:
  application:
    name: Gateway



#入住
eureka:
  client:
    service-url:
      defaultZone: http://lehr.eureka1.com:7001/eureka,http://lehr.eureka2.com:7002/eureka,http://lehr.eureka3.com:7003/eureka
  instance:
    instance-id: Gateway-9527
    prefer-ip-address: true



info:
  module:
    name: QuizHub-GateWay-Zuul
    version: 1.0
  authur: Lehr

management:
  endpoints:
    web:
      exposure:
        #默认暴露所有监控点
        include: '*'


zuul:
  routes:
    guitar.serviceId: GuitarProvider
    guitar.path: /GuitarShop/**
  ignored-services: "*"
  prefix: /quizhub
